name: Pipeline-CD
on:
  # pull_request: # autoriser de jouer les jobs dans les pull request des branches listées ci-dessous
  #   branches: 
  #     - main
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v2

      # pdo_sqlite
      - name: pdo_sqlite
        run: sudo apt-get install php-sqlite3 -y

      #  Action 2 : Install composer
      - name: "Composer install"
        run: |
          curl -sSk https://getcomposer.org/installer | php -- --disable-tls && mv composer.phar --no-plugins --no-scripts /usr/local/bin/composer 
          composer install --no-interaction --no-progress

      #  Action 3 : Install Symfony CLI
      - name: Symfony CLI
        run: |
          curl -sS https://get.symfony.com/cli/installer | bash
          mv /home/runner/.symfony5/bin/symfony /usr/local/bin/symfony

      - name: Deploy Over SSH
        uses: appleboy/ssh-action@master # action qui est dans la marquette place comme actions/checkout@v2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd var/www/symfony-github
            git config pull.rebase false
            git pull 
            sudo apt-get install php-sqlite3 -y
            curl -sSk https://getcomposer.org/installer | php -- --disable-tls && mv composer.phar --no-plugins --no-scripts /usr/local/bin/composer 
            composer install --no-interaction --no-progress
            curl -sS https://get.symfony.com/cli/installer | bash mv /home/runner/.symfony5/bin/symfony /usr/local/bin/symfony
            symfony console d:m:m -n
            APP_ENV=prod APP_DEBUG=0 php bin/console cache:clear 



# curl -sSk https://getcomposer.org/installer | php -- --disable-tls && mv composer.phar /usr/local/bin/composer 
# curl -sS https://get.symfony.com/cli/installer | bash mv /home/runner/.symfony5/bin/symfony /usr/local/bin/symfony