name: Pipeline-CI-2
on:
  push:
    branches: [ main ]
jobs:
  ci2:
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: LS
        run: ls
